## ----------------------------------------------------------------------------
## nexus | NEW_MC208_NN.config.mac
##
## Configuration macro to simulate Tl-208 radioactive decays from the ACTIVE region
## in the NEW detector.
## The NEXT Collaboration
## ----------------------------------------------------------------------------

/control/verbose  1
/run/verbose      1
/event/verbose    0
/tracking/verbose 0

/Generator/Decay0Interface/inputFile       none
/Generator/Decay0Interface/Xe136DecayMode  4
/Generator/Decay0Interface/Ba136FinalState 0
/Generator/Decay0Interface/region          ACTIVE

/Actions/DefaultEventAction/min_energy 1.45 MeV


/Geometry/Next100/max_step_size  1.  mm
/Geometry/Next100/pressure      13.5 bar
/Geometry/Next100/elfield       false


/nexus/persistency/output_file {output_file}
/nexus/persistency/start_id {event}
/nexus/persistency/event_type bb2nu

### JOB CONTROL
/nexus/random_seed {seed}
